name: Build APK

on:
  push:
    branches: [main, master]
    paths:
      - 'apps/react-app/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'apps/react-app/**'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './apps/react-app/package-lock.json'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.0
          ndk: 25.1.8937393

      - name: Accept Android licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build:prod

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Set up signing keystore
        if: github.ref == 'refs/heads/main' || github.event.inputs.build_type == 'release'
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > android/app/release-key.keystore
        
      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          if [ "${{ github.event.inputs.build_type }}" = "release" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: young-eagles-apk-${{ github.run_number }}
          path: |
            apps/react-app/android/app/build/outputs/apk/debug/*.apk
            apps/react-app/android/app/build/outputs/apk/release/*.apk
          retention-days: 30

      - name: Create Release (if main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Young Eagles APK v${{ github.run_number }}
          files: |
            apps/react-app/android/app/build/outputs/apk/release/*.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

